[package]
name = "kv-pack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kv-core.workspace = true
memmap2 = "0.9"
thiserror.workspace = true
hound = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
toml = { workspace = true, optional = true }

[dev-dependencies]
proptest.workspace = true
hound.workspace = true

[features]
default = ["builder"]
builder = ["dep:hound", "dep:serde", "dep:toml"]
