[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
kv-core.workspace = true
kv-pack.workspace = true
anyhow.workspace = true
clap.workspace = true
