[package]
name = "kv-input-linux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kv-core.workspace = true
kv-ring.workspace = true
evdev.workspace = true
libc.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
